name: hodak
description: web developer
meta_description: hodak

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://blog.hodak.pl'
google_analytics: 'UA-4995895-6'
gems: [jekyll-paginate]
permalink: /:title
comments: true

# Details for the RSS feed generator
url:            'blog url'
author:         'Adam Hodowany'
